name: nws_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.5

  # network
  retrofit: '>=3.0.0 <4.0.0'
  logger: any  #for logging purpose

  # browser
  url_launcher: ^6.1.4

  #File Picker
  image_picker: ^0.8.5+3

  # Utils
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.12

  # localizetion
  intl: ^0.17.0
  intl_utils: ^2.6.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # network
  dio: ^4.0.6
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: ^2.1.11
  json_serializable: '>4.4.0'
  curl_logger_dio_interceptor: ^0.0.3

  # Flavor
  flutter_flavorizr: ^2.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "Nws chat dev"

      android:
        applicationId: "vn.com.nws.chatapp.dev"

      ios:
        bundleId: "vn.com.nws.chatapp.dev"

    stg:
      app:
        name: "Nws chat stg"

      android:
        applicationId: "vn.com.nws.chatapp.stg"
      ios:
        bundleId: "vn.com.nws.chatapp.stg"

    prod:
      app:
        name: "Nws chat prod"

      android:
        applicationId: "vn.com.nws.chatapp"
      ios:
        bundleId: "vn.com.nws.chatapp"